export const topics = [
  "All",
  "Focus",
  "Calm",
  "Confidence",
  "Sleep",
  "Self-love",
  "Devotion",
  "Spirituality",
];

// LIVE SUPABASE STORAGE ASSETS
const AMBIENCE_RAIN = "https://tpoilisvdacxgryhoujg.supabase.co/storage/v1/object/public/antara-audio/ambience/rain.mp3";
const AMBIENCE_WAVES = "https://tpoilisvdacxgryhoujg.supabase.co/storage/v1/object/public/antara-audio/ambience/waves.mp3";
const AMBIENCE_FOCUS = "https://tpoilisvdacxgryhoujg.supabase.co/storage/v1/object/public/antara-audio/sessions/focus.mp3";

const SESSION_DEEP_FOCUS = "https://tpoilisvdacxgryhoujg.supabase.co/storage/v1/object/public/antara-audio/sessions/deep-focus.mp3";
const SESSION_FOCUS = "https://tpoilisvdacxgryhoujg.supabase.co/storage/v1/object/public/antara-audio/sessions/focus.mp3";

export const programs = [
  {
    id: "p1",
    title: "Deep Focus",
    topic: "Focus",
    description: "Settle distractions and return to what matters.",
    duration: 10,
    image: "https://thumbs.dreamstime.com/b/person-deep-meditation-surrounded-psychic-waves-emanating-their-mind-life-creation-chakras-focus-point-302603396.jpg",
    audioUrl: SESSION_DEEP_FOCUS,
    ambienceUrl: AMBIENCE_FOCUS,
  },
  {
    id: "p2",
    title: "Calm Mind Reset",
    topic: "Calm",
    description: "A quick breathing exercise to reset your nervous system.",
    duration: 8,
    image: "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1V4HLS.img?w=700&h=400&m=4&q=54",
    audioUrl: SESSION_FOCUS, // Wired to your live Supabase focus audio
    ambienceUrl: AMBIENCE_RAIN,
  },
  {
    id: "p3",
    title: "Morning Confidence",
    topic: "Confidence",
    description: "Start your day with powerful affirmations.",
    duration: 6,
    image: "https://stevenwebb.com/wp-content/uploads/2024/02/Morning-Confidence-and-Self-Belief-Guided-Meditation-by-Steven-WebbImage.jpg",
    audioUrl: "/programs/morning-confidence.mp3",
    ambienceUrl: null,
  },
  {
    id: "p4",
    title: "Sleep Softly",
    topic: "Sleep",
    description: "Drift off into a deep, restorative sleep.",
    duration: 20,
    image: "https://images.indianexpress.com/2025/10/sleep_0caaca.png",
    audioUrl: "/programs/sleep-softly.mp3",
    ambienceUrl: AMBIENCE_WAVES,
  },
  {
    id: "p5",
    title: "Come Home to Yourself",
    topic: "Self-love",
    description: "A gentle reminder of your own inner worth.",
    duration: 12,
    image: "https://inspireambitions.com/wp-content/uploads/2023/10/Love-Yourself-11.jpg",
    audioUrl: "/programs/come-home-to-yourself.mp3",
    ambienceUrl: "/audio/ambience/tanpura.mp3",
  },
  {
    id: "p6",
    title: "Morning Devotion",
    topic: "Devotion",
    description: "Begin your day with gratitude and sacred chants.",
    duration: 15,
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/morning-devotion.mp3",
    ambienceUrl: "/audio/ambience/tanpura.mp3",
  },
  {
    id: "p7",
    title: "Spiritual Awakening",
    topic: "Spirituality",
    description: "Connect deeply with the universe and your higher self.",
    duration: 25,
    image: "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/spiritual-awakening.mp3",
    ambienceUrl: AMBIENCE_FOCUS,
  },
  {
    id: "p8",
    title: "Chants of Peace",
    topic: "Devotion",
    description: "Immerse yourself in deeply relaxing spiritual mantras.",
    duration: 10,
    image: "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/chants-of-peace.mp3",
    ambienceUrl: AMBIENCE_RAIN,
  },
  {
    id: "p9",
    title: "Inner Divinity",
    topic: "Spirituality",
    description: "A guided journey to find the sacred light within.",
    duration: 18,
    image: "https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/inner-divinity.mp3",
    ambienceUrl: AMBIENCE_WAVES,
  },
  {
    id: "p10",
    title: "Sacred Silence",
    topic: "Spirituality",
    description: "Embrace the profound stillness of your own consciousness.",
    duration: 20,
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/sacred-silence.mp3",
    ambienceUrl: null,
  },
  {
    id: "p11",
    title: "Temple Bells",
    topic: "Devotion",
    description: "A resonant sequence of singing bowls and sacred sounds.",
    duration: 12,
    image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/temple-bells.mp3",
    ambienceUrl: "/audio/ambience/tanpura.mp3",
  },
  {
    id: "p12",
    title: "Divine Grace",
    topic: "Devotion",
    description: "Surrender your worries and invite divine energy in.",
    duration: 15,
    image: "https://img.magnific.com/premium-photo/guru-purnima-celebration-india-honoring-gurus-with-devotion-spirituality_978786-43546.jpg",
    audioUrl: "/programs/divine-grace.mp3",
    ambienceUrl: null,
  },
  {
    id: "p13",
    title: "Cosmic Connection",
    topic: "Spirituality",
    description: "Feel your ties to the stars and the expansive universe.",
    duration: 30,
    image: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/cosmic-connection.mp3",
    ambienceUrl: AMBIENCE_FOCUS,
  },
  {
    id: "p14",
    title: "Evening Aarti",
    topic: "Devotion",
    description: "Wind down with traditional evening prayers and gratitude.",
    duration: 10,
    image: "https://images.unsplash.com/photo-1510784722466-f2aa9c52fff6?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/evening-aarti.mp3",
    ambienceUrl: "/audio/ambience/tanpura.mp3",
  },
  {
    id: "p15",
    title: "Zen Mind",
    topic: "Calm",
    description: "Clear away the mental clutter and find your center.",
    duration: 10,
    image: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/zen-mind.mp3",
    ambienceUrl: AMBIENCE_RAIN,
  },
  {
    id: "p16",
    title: "Deep Healing",
    topic: "Self-love",
    description: "Nurture your emotional wounds with gentle compassion.",
    duration: 22,
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/deep-healing.mp3",
    ambienceUrl: AMBIENCE_WAVES,
  },
  {
    id: "p17",
    title: "Unshakeable",
    topic: "Confidence",
    description: "Build an armor of unshakeable self-belief.",
    duration: 8,
    image: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/unshakeable.mp3",
    ambienceUrl: AMBIENCE_FOCUS,
  },
  {
    id: "p18",
    title: "Flow State",
    topic: "Focus",
    description: "Unlock deep productivity and effortless concentration.",
    duration: 45,
    image: "https://images.unsplash.com/photo-1523712999610-f77fbcfc3843?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/flow-state.mp3",
    ambienceUrl: AMBIENCE_RAIN,
  },
  {
    id: "p19",
    title: "Midnight Rest",
    topic: "Sleep",
    description: "Guided relaxation to beat insomnia and quiet the mind.",
    duration: 35,
    image: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/midnight-rest.mp3",
    ambienceUrl: AMBIENCE_WAVES,
  },
  {
    id: "p20",
    title: "Mantra Meditation",
    topic: "Devotion",
    description: "Repeat powerful syllables to tune your frequency.",
    duration: 15,
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/mantra-meditation.mp3",
    ambienceUrl: "/audio/ambience/tanpura.mp3",
  },
  {
    id: "p21",
    title: "Soul Journey",
    topic: "Spirituality",
    description: "Travel inward to explore the landscape of your soul.",
    duration: 20,
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/soul-journey.mp3",
    ambienceUrl: null,
  },
  {
    id: "p22",
    title: "Ocean Breath",
    topic: "Calm",
    description: "Sync your breathing with the rhythm of the tides.",
    duration: 5,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/ocean-breath.mp3",
    ambienceUrl: AMBIENCE_WAVES,
  },
  {
    id: "p23",
    title: "Radiate Light",
    topic: "Self-love",
    description: "Expand your aura and project positivity outward.",
    duration: 10,
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/radiate-light.mp3",
    ambienceUrl: AMBIENCE_FOCUS,
  },
  {
    id: "p24",
    title: "Divine Love",
    topic: "Devotion",
    description: "Open your heart chakra to universal and divine love.",
    duration: 18,
    image: "https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/divine-love.mp3",
    ambienceUrl: "/audio/ambience/tanpura.mp3",
  },
  {
    id: "p25",
    title: "Astral Sleep",
    topic: "Sleep",
    description: "Float through the cosmos into a heavy, deep slumber.",
    duration: 60,
    image: "https://images.unsplash.com/photo-1538370965046-79c0d6907d47?w=800&auto=format&fit=crop&q=60",
    audioUrl: "/programs/astral-sleep.mp3",
    ambienceUrl: AMBIENCE_RAIN,
  }
];